name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
